### ISSUE TITLE
Stock quantities do not save

### ISSUE THREAD

**Issue by takj** [vimes1984/woocommerce_variable_stock_management#1]
Hi there,

I've recently downloaded this plugin but it doesn't seem to be working on my installation. When I enter the amount to be deducted and/or select 'yes' / 'no' - none of these values save.  When the product is updated / saved, the value just return to default?

Really need a plugin with these features, would you be willing to work with us on making it work for us please?

**Comment by vimes1984** [comment]
Sure send me a PM with your skype and I'll grab the ftp and take a look this latest version should have fixed the non saving value..

**Comment by vimes1984** [comment]
Use this version the one on wordpress is one release behind by the looks of things the lines you need changing are here: https://github.com/vimes1984/woocommerce_variable_stock_management/commit/075d444a74bec38ff92938946eb2643b3c316170
:D updated feb 18th but didn't commit to wordpress for some reason...

**Comment by takj** [comment]
Many thanks!   Awesome Plugin!

**Comment by vimes1984** [comment]
It worked?

**Comment by vimes1984** [comment]
Also updated the wordpress version if you needed :+1:

**Comment by vimes1984** [comment]
If you liked write me a nice review :D

**Comment by takj** [comment]
Yes after re-install.  Just placed a test order on the below page and selected 1 adult and 2 children. Thus reducing the stock from 12 to 9.

I'm using it here:
http://www.jerseyyachtcharter.co.uk/yacht-charters/half-day-south-coast-cruise/

**Comment by vimes1984** [comment]
https://wordpress.org/support/view/plugin-reviews/woocommerce-variable-stock-management

**Comment by vimes1984** [comment]
Nice :D lovely to here it's useful to someone I couldn't find any plugins to do it so I built my own. Glad to hear ti helped mate if you need anything else let me know! 
Chris

**Comment by takj** [comment]
Will write a Ma'Husive review and include the scenario I need the plugin for. There must be a huge demand for this feature surely??!!

**Comment by vimes1984** [comment]
I thought there must be a huge demmand for it... But couldn't find any viable solution that did, I'm using it on a e-commerce that sells cigars in packs and single all from the same total stock... It didn't make any sense that this feature wasn't included

**Comment by takj** [comment]
It's perfect for anyone selling tickets really!  There is WooTickets available but you have to use it with the events feature and can't use its functionality on products. Personally I think your plugin should come as standard with WooCommerce it's that useful..

One other thing that restricts me in WC is the 'Link All Variations' button as it will only allow you to create 50 variations at once.  Do you know of a workaround for this at all?

**Comment by vimes1984** [comment]
yeah i got around this by importing products and variations from a csv... 
it's a bit of a pain but I do have a importer in here as well, you'll have to have some knowledge of php, but you can find it here:  https://github.com/vimes1984/woocommerce_variable_stock_management/blob/master/includes/class-import-categories.php
chris

**Comment by takj** [comment]
Hi Chris, really sorry to bother you again. I'm having a similar problem as before. This time some save and others don't.

Any chance you could assist with this please?

**Comment by vimes1984** [comment]
I suspect the ones that don't where created before you updated the plugin? wanna send me the ftp logins? 
add me on skype if you want my handle is the same

**Comment by takj** [comment]
Ah good shout, sounds like that could be the reason.  Thanks again for your help

Is this all you need?

Username: jerseyyachtcharter.co.uk
Password: T!Ej/DhE!
FTP Server: ftp.jerseyyachtcharter.co.uk
FTP Server IP: 79.170.44.23

**Comment by vimes1984** [comment]
DO NOT POST YOUR FTP PUBLICLLY!!!!!

**Comment by vimes1984** [comment]
email me the wordpress logins please churchill.c.j [at] gmail.com

**Comment by vimes1984** [comment]
which ones aren't working?

**Comment by takj** [comment]
Product ID 13660

The variables towards the end of the list, there about 10 of them from #14135 - #14146

**Comment by vimes1984** [comment]
the variations must have a SKU and a price...
but it looks like it's not the plugin's issue I've just edited the any/any variations and it works fine none of the values in the variations save not the sku or anything...

**Comment by vimes1984** [comment]
http://www.jerseyyachtcharter.co.uk/wp-admin/post.php?post=13660&action=edit&message=1

**Comment by takj** [comment]
Those at the top of the list work fine. At the bottom of the list they don't seem to save. Try the very bottom one  #14146

**Comment by vimes1984** [comment]
Yeah I noticed that... but they dont' save any data not just the deduct or not data,..... 
try adding the product in again...

**Comment by vimes1984** [comment]
hows it going?

**Comment by takj** [comment]
Tried deleting one of the variables that wasn't working and re adding it but won't save another variable now. So will do as you suggest and create another produst called TEST

**Comment by vimes1984** [comment]
yes I do somethings gone wrong obviously

**Comment by takj** [comment]
Seems to be fine mate!

Guess it's something to do with that product being created pre plugin update as you suggested

http://www.jerseyyachtcharter.co.uk/wp-admin/post.php?post=14172&action=edit&message=6

**Comment by vimes1984** [comment]
:D loevly to hear if you need anything else let me know

**Comment by takj** [comment]
Thanks again Chris!

**Comment by takj** [comment]
Hi Chris, I've just created the new product but 10 out 48 haven't saved. Any ideas mate?

Sorry to keep pestering but as mentioned before, I really need this feature.  Do you think it has anything to do with the fact that I'm using so many variables?

You can get me on Skype if easier  facebook:tom.undy.1

http://www.jerseyyachtcharter.co.uk/wp-admin/post.php?post=14172&action=edit&message=1

**Comment by vimes1984** [comment]
Just added you on skype

**Comment by vimes1984** [comment]
this is a problem with woo not this plugin: 
http://docs.woothemes.com/document/problems-with-large-amounts-of-data-not-saving-variations-rates-etc/

**Comment by takj** [comment]
Ah ok cool mate thanks once again Chris. I'm going to limit the number of variables I use.

**Comment by MarkDonald** [comment]
i have a problem with this plugin it says "this plugin does not have a valid header" when i tried to activate this plugin it says .. class GQ.PHP not found in my plugins .

plzzzz help me with this ..

**Comment by vimes1984** [comment]
can you uninstall and reinstall please...

**Comment by MarkDonald** [comment]
when im finish to install it , and then ill go to installed plugins and activate it says .

Plugin could not be activated because it triggered a fatal error.
Fatal error: Class 'GQ' not found in C:\xampp\htdocs\wordpress\wp-content\plugins\woocommerce_variable_stock_management-master\gq.php on line 42


plss help .. i need this plugin because this will be the solve of my problem but not work for me :'(

**Comment by vimes1984** [comment]
OK remove the plugin completely from you site the re add it in from the plugin repositry... I've just installed it from a from the plugin repo and it's working fine here..

**Comment by MarkDonald** [comment]
how can i add it from the plugin repository?? sorry im just a beginner but i search about plugin repository in google and youtube but nothing show i dont know where can i find plugin repo in my wordpress site ...

**Comment by vimes1984** [comment]
mate you need to remove the plugin from your site completely then re add
it:
https://www.youtube.com/watch?v=AXM1QgMODW0

**Comment by Risha91** [comment]
Hey i would really make use of your plugin, however i tried installing it twice, once from wordpress directly and second time by dowloading master.zip from github. I recieved same error both times when i tried to activate the plugin:
Plugin could not be activated because it triggered a fatal error.
Fatal error: Class 'GQ' not found in C:\wamp\www\folder-name\wp-content\plugins\woocommerce_variable_stock_management-master\GQ.php on line 43

Any updates on this issue?

**Comment by vimes1984** [comment]
I'm moving this here: https://github.com/vimes1984/woocommerce_variable_stock_management/issues/4

**Comment by nummell** [comment]
Hi,

This plugin does exactly what I need but It doesn´t save product quantities...
I have 2 variations, 1 to remove only 1 item from stock and another to remove 20. Both of them remove 2!

I´m using latest wordpress and latest woocommerce, tried with plugin from wp repo and from github, none of them works, can you help me?

Thx in advance

**Comment by vimes1984** [comment]
the variation you are apllying it to MUST have all the firleds filling in
such as SKU and the rest..

**Comment by nummell** [comment]
Already tried and still doesn´t save... 
Everything is updated, all plugins, woocomerce and wordpress, I have no idea why it does´t save!

**Comment by andrewinfinite** [comment]
HI I have downloaded the latest version from github and when I enter the amount to be deducted select 'yes'  - none of these values save. can you take a look on my site and see if you can solve the issue on my end

**Comment by udarts** [comment]
Hi there, I have probably the same issue as some have here.
I have a product with a main stock of 3 and and 3 variables, with each 1 stock.

I have the stock management set on both main and variable.
So when I select a variable on that product, and checkout, it should deduct on the main and variable stock. But it only deducts on the variable stock.

Any idea about this issue?

Thanks.

**Comment by vimes1984** [comment]
I no longer maintain this!
