### ISSUE TITLE
Unable to get plugin to work

### ISSUE THREAD

**Issue by sikchik** [vimes1984/woocommerce_variable_stock_management#2]
Hi!

I try everything.. literally everything.. But i still can't get this plugin to work.
I tried plugin from wordpress.org as well as this one on github. I have updated wordpress and woocommerce to the last version. 

Any suggestion why plugin does not work? It is compatible with latest woocommerce version?

Thanks in advance!

**Comment by vimes1984** [comment]
it should be totally compatible with the latest version of Woo and Wordpress, can you explain exactly what isn't working?

**Comment by vimes1984** [comment]
Yup I've just checked on on WOO : Version 2.3.7 and it works fine...

**Comment by sikchik** [comment]
Hi,

It just don't work. I can select "YES" for "Deduct from stock total".. Also i can set "Amount to deduct from total" but always reduce quantity only for 1 item.

Weird .. i will try to install fresh copy of WP and woocommerce and try again..

Thanks..

**Comment by vimes1984** [comment]
keep me posted please we'll figure it out! 
Chris

**Comment by vimes1984** [comment]
how is it going?

**Comment by sikchik** [comment]
Hi..

Works fine on fresh installation. Still have no idea why plugin doesn't work on "old" installation. Are there any settings which affect on this plugin? Maybe any important settings needs to be "checked" in woocommerce settings or product edit page?

Thanks..

**Comment by vimes1984** [comment]
If i remeber correctly the products need to have a sku.... 
but apart from that it should just work simple as. 
do you have any other plugins on the old installation that may interefere with the checkout processs?

**Comment by sikchik** [comment]
I've deleted all products and then added products from scratch. And now it works like a charm! 

Thanks for awesome plugin and fast support!

**Comment by vimes1984** [comment]
Lovely to here! 
if you have any other problems let me know!

**Comment by vimes1984** [comment]
Fell free to leave a review on the plugin page aswell it's much appriciated! 
https://wordpress.org/support/view/plugin-reviews/woocommerce-variable-stock-management
