### ISSUE TITLE
Able to order more than what is available

### ISSUE THREAD

**Issue by avsync** [vimes1984/woocommerce_variable_stock_management#3]
Hi.

Sorry to re-post, I posted over at wordpress.org but then saw your request for bugs to be tracked here.

I have identified an issue with the ability to order more than what is available in stock, for instance:

Main stock quantity set to 100.

I have product variations for quantities of 10, 50 and 100. What I would hope for is that order quantities would be limited to 10x10, 2x50 and 1x100. What is happening is that you are able to order up to 100x10, 100x50 and 100x100.

**Comment by vimes1984** [comment]
hello there... 
Yes I did realise this might occur I'll open it up this afternoon and take a look as soon as i have something I'll release a new version should be by this eve gmt+1. 
Chris

**Comment by avsync** [comment]
Awesome! Thanks for creating this plugin Chris, it's a hidden gem at the moment which I'm sure will become very popular. Really appreciate the willingness to assist with the issues.

**Comment by vimes1984** [comment]
Ok mate ! 
I got it done ASAP been bogged down with work but hey ho :D 
This will now check against the amount you have in stock NOT including the amount they currently have in stock, and if it goes over it'll just spit out a custom error message. 
It'll also allow backorders still. 
What this won't do it update the onpage JS to reflect what variation you currently have selected on the product page it will always show the total amount ... 
That is going to require a little more work a bit of front end JS and such. 
if you give it a go let me know! 
Feel free to fork this repo on here and give it a go I'll pull it in!

**Comment by vimes1984** [comment]
Oh the version you want is 1.0.5 :D

**Comment by vimes1984** [comment]
fell free to leave a review on the main plugin every little helps! 
https://wordpress.org/support/view/plugin-reviews/woocommerce-variable-stock-management

**Comment by avsync** [comment]
Thanks for the quick update! I did a test and the issue of being able to order more than what is in stock is sorted and works great. Another issue has popped up though... now when you try to "over order" on other simple products that aren't making use of the plugin the following error is displayed on the frontend, It disappears when when the plugin is disabled.

Warning: Missing argument 4 for catchaddtocart::filter_woocommerce_add_to_cart_validation() in /home/vallegob/public_html/wp-content/plugins/woocommerce-variable-stock-management/includes/class-catch-add-to-cart.php on line 87

Warning: Missing argument 5 for catchaddtocart::filter_woocommerce_add_to_cart_validation() in /home/vallegob/public_html/wp-content/plugins/woocommerce-variable-stock-management/includes/class-catch-add-to-cart.php on line 87

Warning: Invalid argument supplied for foreach() in /home/vallegob/public_html/wp-content/plugins/woocommerce/includes/class-wc-product-variation.php on line 144

**Comment by vimes1984** [comment]
shit I'll fix in a min..!

**Comment by avsync** [comment]
Thanks. Checked and it actually also happens even when adding normal quantities of a simple product to cart.

**Comment by vimes1984** [comment]
version 1.0.6 should have fixed it :D

**Comment by avsync** [comment]
You're a champ! 1.0.6 cleared up the php error messages :-) Really sorry to be a pest but I've spotted something else now... 

If you choose a variation quantity that is in available stock, you can hit add to cart multiple times and it will go beyond the value of what is in available without restriction or error pop up. This can also be done in the cart by increasing the qty with no restriction or pop up.

**Comment by vimes1984** [comment]
yeah I know by this: This will now check against the amount you have in stock NOT including the amount they currently have in stock, and if it goes over it'll just spit out a custom error message. 
I meant currently in CART not stock... 
I've yet to implement the cart checker... 
if you fancy taking a bash at it the function that does the checking is : https://github.com/vimes1984/woocommerce_variable_stock_management/blob/master/includes/class-catch-add-to-cart.php
line 87 the string you'll need to do the checking "should" be in line 105 :D 
if you don't dare I'll be back on monday and I can take a look then! 
if you do take a chance just fork this repo and I'll be glad to patch in the fix. 
Chris

**Comment by avsync** [comment]
Thanks Chris. I'll fork and have a look but can almost guarantee it'll still be untouched as my coding knowledge is very basic. Have a great weekend :-)
