### ISSUE TITLE
windows unable to install due to same name error.

### ISSUE THREAD

**Issue by vimes1984** [vimes1984/woocommerce_variable_stock_management#4]
Moved from: https://github.com/vimes1984/woocommerce_variable_stock_management/issues/1
REF "Risha91 " : Hey i would really make use of your plugin, however i tried installing it twice, once from wordpress directly and second time by dowloading master.zip from github. I recieved same error both times when i tried to activate the plugin:
Plugin could not be activated because it triggered a fatal error.
Fatal error: Class 'GQ' not found in C:\wamp\www\folder-name\wp-content\plugins\woocommerce_variable_stock_management-master\GQ.php on line 43

Any updates on this issue?

**Comment by vimes1984** [comment]
this is due to the files being called the "same" one caps one not.

**Comment by vimes1984** [comment]
give me 10 mins I'll see if i can switch them...

**Comment by vimes1984** [comment]
OK version 1.0.7 should have fixed this error please let me know and I can close this... 
Chris

**Comment by Risha91** [comment]
I just downloaded newest version and replacing the old files with new ones. It seems that you succesfully fixed the problem as i activated it without any problems. Big thanks for such a fast response!

**Comment by vimes1984** [comment]
:D no worries mate I had this issue in the back of my mind for a week or so. It's down to not being allowed to have to file names the same one with caps and one in lowercase windows sees them as the same file my linux box doesn't :D 
A review on  https://wordpress.org/support/view/plugin-reviews/woocommerce-variable-stock-management would do me the world of good if you have a min! 
if you have anything else just drop me a bell! 
Chris
