### ISSUE TITLE
Update product quantity on all products page

### ISSUE THREAD

**Issue by Risha91** [vimes1984/woocommerce_variable_stock_management#5]
Hey there!

Im selling the same product in three different weight variations, for example 100grams, 250grams and 500grams. Lets say i set the product quantity to 1kg which is 1000grams and someone buys 250grams. This plugin will correctly deduct bought amount when you are editing the item and show 750grams, but if you click on "Products" tab which is showing all products in store, the quantity will still be the same as before purchase which is 1000grams. As i said once you click edit on product you can see the deducted quantity but not on all products admin display page. Is there a way to update that quantity too as it is very important for keeping track of products quantity.

**Comment by vimes1984** [comment]
the product should be updated across the board mate not just on the edit tab... 
refresh the page and clear the browser cache.

**Comment by Risha91** [comment]
Well sadly it is not working for me untill i save the product after editing it. As i said it works on the product edit page where it shows correct quantity but on the all products page it shows the old quantity. I cleared all caches and im using the latest version of wordpress, woocommerce and your plugin.

**Comment by vimes1984** [comment]
ok lets see give me two mins

**Comment by vimes1984** [comment]
Ok that took a little longer than two mins mate! 
version 1.1.2 should have fixed it what a weird error thank you for bring it to my attention! 
Chris

**Comment by vimes1984** [comment]
let me know if that fixes it for you and I'll close this issue

**Comment by Risha91** [comment]
Sorry for a bit late reply, i just tested new version and the stock is now correctly updated on "all products" display page. There was an error info tho, after i activated the plugin, saying that the plugin created 2400 unexpected charachters or something and that i should disable it if it will cause problems. Just so u know. Thank you for fixing it so fast, keep up the good work!

**Comment by vimes1984** [comment]
a review???
:P

**Comment by Risha91** [comment]
Already posted one on wordpress plugin home page yesterday. :)

**Comment by vimes1984** [comment]
your a star mate thank you :D
